# name: Auto Merge PR

# on:
#   pull_request:
#     branches:
#       - master

# jobs:
#   automerge:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Auto merge PR if CI is successful
#         uses: pascalgn/automerge-action@v0.16.3
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



name: Auto PR + Auto Merge

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head: develop
          base: master
          title: "Auto PR: develop → master"
          body: "Cette PR a été créée automatiquement après un push sur develop."
          labels: automated-pr
          draft: false

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash  # ou merge, rebase selon ta préférence
