name: Auto Merge PR

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge PR if CI is successful
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
