name: Create Pull Request

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master         # destination de la PR
          head: develop        # source de la PR
          title: "Auto PR: develop → master"
          body: "Cette PR a été créée automatiquement après un push sur develop."
          labels: automated-pr
          draft: false
