name: Auto PR to master

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop   # <-- source
          base: master      # <-- destination
          title: "Auto PR: develop → master"
          body: "Cette PR a été créée automatiquement après un push sur develop."
          labels: automated-pr
